"""empty message

Revision ID: d9da1d3e415c
Revises: 
Create Date: 2023-07-26 09:27:19.161867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9da1d3e415c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('mother', sa.String(), nullable=True),
    sa.Column('father', sa.String(), nullable=True),
    sa.Column('partner', sa.String(), nullable=True),
    sa.Column('children', sa.String(), nullable=True),
    sa.Column('sibling', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_families_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('looms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lineage', sa.String(), nullable=True),
    sa.Column('photos', sa.String(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_looms_event_id_events')),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_looms_family_id_families')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('lname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('loom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loom_id'], ['looms.id'], name=op.f('fk_users_loom_id_looms')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('looms')
    op.drop_table('families')
    op.drop_table('events')
    # ### end Alembic commands ###
